"""
Pydantic schemas for API validation and serialization.
"""
from app.schemas.base import (
    BaseSchema,
    TimestampSchema,
    PaginationParams,
    PaginationMeta,
    PaginatedResponse,
    MessageResponse,
    ErrorResponse,
    SuccessResponse,
    IDResponse,
)
from app.schemas.user import (
    UserCreate,
    UserRegister,
    UserLogin,
    UserUpdate,
    UserPasswordChange,
    UserPasswordReset,
    UserPasswordResetConfirm,
    UserResponse,
    UserPublicResponse,
    UserListResponse,
    TokenResponse,
    TokenRefresh,
    EmailVerification,
    PasswordResetRequest,
    PasswordReset,
    UserStats,
)
from app.schemas.course import (
    CourseCreate,
    CourseUpdate,
    CourseResponse,
    CourseListItem,
    CourseDetailResponse,
    CoursePublish,
    CourseFilterParams,
    CourseStats,
)
from app.schemas.content import (
    ModuleCreate,
    ModuleUpdate,
    ModuleResponse,
    ModuleWithLessons,
    ModuleReorder,
    ModuleOrderItem,
    LessonCreate,
    LessonUpdate,
    LessonResponse,
    LessonListItem,
    LessonComplete,
    LessonProgress,
    LessonReorder,
    LessonOrderItem,
)
from app.schemas.enrollment import (
    EnrollmentCreate,
    EnrollmentResponse,
    EnrollmentWithCourse,
    EnrollmentFilterParams,
    ProgressCreate,
    ProgressUpdate,
    ProgressResponse,
    ProgressWithLesson,
    CourseProgress,
    LearningStats,
)
from app.schemas.payment import (
    PaymentCreate,
    PaymentResponse,
    PaymentWithCourse,
    StripeCheckoutSession,
    CheckoutSessionCreate,
    CheckoutSessionResponse,
    PaymentRefund,
    PaymentFilterParams,
    PaymentStats,
    CertificateResponse,
    CertificateWithCourse,
    CertificateVerify,
    CertificateVerifyResponse,
    CertificateFilterParams,
)
from app.schemas.resource import (
    ResourceCreate,
    ResourceUpdate,
    ResourceResponse,
    ResourceListItem,
    ResourceFilterParams,
    BookmarkCreate,
    BookmarkUpdate,
    BookmarkResponse,
    BookmarkWithResource,
    BookmarkFilterParams,
    ResourceStats,
)

# Rebuild models with forward references
CourseDetailResponse.model_rebuild()
EnrollmentWithCourse.model_rebuild()
ProgressWithLesson.model_rebuild()
PaymentWithCourse.model_rebuild()
CertificateWithCourse.model_rebuild()

__all__ = [
    # Base
    "BaseSchema",
    "TimestampSchema",
    "PaginationParams",
    "PaginationMeta",
    "PaginatedResponse",
    "MessageResponse",
    "ErrorResponse",
    "SuccessResponse",
    "IDResponse",
    # User
    "UserCreate",
    "UserRegister",
    "UserLogin",
    "UserUpdate",
    "UserPasswordChange",
    "UserPasswordReset",
    "UserPasswordResetConfirm",
    "UserResponse",
    "UserPublicResponse",
    "UserListResponse",
    "TokenResponse",
    "TokenRefresh",
    "EmailVerification",
    "PasswordResetRequest",
    "PasswordReset",
    "UserStats",
    # Course
    "CourseCreate",
    "CourseUpdate",
    "CourseResponse",
    "CourseListItem",
    "CourseDetailResponse",
    "CoursePublish",
    "CourseFilterParams",
    "CourseStats",
    # Content
    "ModuleCreate",
    "ModuleUpdate",
    "ModuleResponse",
    "ModuleWithLessons",
    "ModuleReorder",
    "ModuleOrderItem",
    "LessonCreate",
    "LessonUpdate",
    "LessonResponse",
    "LessonListItem",
    "LessonComplete",
    "LessonProgress",
    "LessonReorder",
    "LessonOrderItem",
    # Enrollment
    "EnrollmentCreate",
    "EnrollmentResponse",
    "EnrollmentWithCourse",
    "EnrollmentFilterParams",
    "ProgressCreate",
    "ProgressUpdate",
    "ProgressResponse",
    "ProgressWithLesson",
    "CourseProgress",
    "LearningStats",
    # Payment
    "PaymentCreate",
    "PaymentResponse",
    "PaymentWithCourse",
    "StripeCheckoutSession",
    "CheckoutSessionCreate",
    "CheckoutSessionResponse",
    "PaymentRefund",
    "PaymentFilterParams",
    "PaymentStats",
    "CertificateResponse",
    "CertificateWithCourse",
    "CertificateVerify",
    "CertificateVerifyResponse",
    "CertificateFilterParams",
    # Resource
    "ResourceCreate",
    "ResourceUpdate",
    "ResourceResponse",
    "ResourceListItem",
    "ResourceFilterParams",
    "BookmarkCreate",
    "BookmarkUpdate",
    "BookmarkResponse",
    "BookmarkWithResource",
    "BookmarkFilterParams",
    "ResourceStats",
]
